name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-run:
    runs-on: ubuntu-latest
    steps:
      - name: Set up MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: '8.0'
          mysql user: 'test'
          mysql password: '1234'

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2.12'

      - name: checkout-project
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: php-actions/composer@v6

      - name: create-database
        run: php bin/console d:d:c

      - name: migration-database
        run: php bin/console make:migration

      - name: migrate
        run: php bin/console d:m:m
